### ISSUE TITLE
Populating the SQL database

### ISSUE THREAD

**Issue by eleqtrizit** [ZairaRiv/ESNS#3]
Using comma delimited files (.csv) to populate a MySQL database.

**Comment by ZairaRiv** [comment]
Can you explain a little about what you mean by this?

**Comment by eleqtrizit** [comment]
I put test data in the database.

________________________________

**Comment by eleqtrizit** [comment]
There is a new directory called projectextras.  You can text the test.csv file that was used to put data into the studentDatabase using MySQL Bench.

________________________________

**Comment by eleqtrizit** [comment]
Text = see.

________________________________

**Comment by ZairaRiv** [comment]
Oh okay, where at?
You put test data into all the databases, even the building one?

**Comment by ZairaRiv** [comment]
Nevermind, I finally found it. I need to organize this better.

Thanks!
