### ISSUE TITLE
Responsive page

### ISSUE THREAD

**Issue by majid-farhadloo** [ZairaRiv/ESNS#8]
I added codes that adjust both max and min height and width for the different devices, but somehow it did not go trough. Rn, I just added different query for iphones and desktop. Please take a look at it and let me know what changes need to do.

**Comment by ZairaRiv** [comment]
Where exactly are those changes at? 
I took a look and it is not a new commit, so it must mean that you adjusted these somewhere on the page. 
Can you direct me to the file? 
Thanks.

**Comment by majid-farhadloo** [comment]
Hi,

Let me I m gonna take a look at it.
Btw, I wonder if we can get together before the class and take a look at
what we want to present. I was thinking at 1:30 in library. Does it work
for you?

**Comment by ZairaRiv** [comment]
Okay take a look and you can let me know tomorrow.
1:30 works for me, text me when you get there.

**Comment by majid-farhadloo** [comment]
Hi,

I m on my way to library, will you be able to meet up?

Thanks, Majid

**Comment by ZairaRiv** [comment]
Yes, I'll head over there right now. Meet me on the 2nd floor?
